### ISSUE TITLE
Use <form> to wrap forms with inputs

### ISSUE THREAD

**Issue by Chkalov-Valerii** [Rybakov-Oleg/teahcing#1]
https://github.com/Rybakov-Oleg/teahcing/blob/8a667d3dfe0880d12647b856306399a675c9b01f/fg.html#L15

**Comment by Rybakov-Oleg** [comment]
https://github.com/Rybakov-Oleg/teahcing/commit/a1b25550f7ace62e80899e8db25779b7fd90bd16

**Comment by Chkalov-Valerii** [comment]
You still can use <div> inside <form> tags, so you could just wrap this <div> with a <form>, but this is kinda great decision anyway.
Closing issue.
Thanks.
