### ISSUE TITLE
The text inside <div> is related to input fields. It those cases your <label>

### ISSUE THREAD

**Issue by Chkalov-Valerii** [Rybakov-Oleg/teahcing#2]
Use <label> with "for" attr. You may relate some text to an input field by its ID and label`s attr "for"

https://github.com/Rybakov-Oleg/teahcing/blob/8a667d3dfe0880d12647b856306399a675c9b01f/fg.html#L16

**Comment by Rybakov-Oleg** [comment]
https://github.com/Rybakov-Oleg/teahcing/commit/229ba0e8a5573749bd30f566747e221239e5e830

Like that?

**Comment by Chkalov-Valerii** [comment]
Made some comments.
Please fix while you can.

**Comment by Rybakov-Oleg** [comment]
https://github.com/Rybakov-Oleg/teahcing/commit/01965a59c076f5163f2201f37b0f1c4e0f7427fa

**Comment by Chkalov-Valerii** [comment]
Great!
Take a note, each time you pressing submit button, your browser`s URL will change. Its because, now you sending GET request from your form to the native server of the site. 
By this you may be reassured that form is valid and operational from the SEO perspective.

Closing Issue
