### ISSUE TITLE
Avoid using input without "name" attr

### ISSUE THREAD

**Issue by Chkalov-Valerii** [Rybakov-Oleg/teahcing#3]
"name" attr is a name of variable that's related to input's value.
Also, avoid using <input> tags outside forms.

https://github.com/Rybakov-Oleg/teahcing/blob/8a667d3dfe0880d12647b856306399a675c9b01f/fg.html#L17

**Comment by Rybakov-Oleg** [comment]
https://github.com/Rybakov-Oleg/teahcing/commit/01965a59c076f5163f2201f37b0f1c4e0f7427fa

**Comment by Chkalov-Valerii** [comment]
Great, now form can submit some data to the server, even without any line of script!
