### ISSUE TITLE
Empty "id" attr

### ISSUE THREAD

**Issue by Chkalov-Valerii** [Rybakov-Oleg/teahcing#4]
Avoid using empty "id" attr, it may case errors for SEO crawlers 

https://github.com/Rybakov-Oleg/teahcing/blob/8a667d3dfe0880d12647b856306399a675c9b01f/fg.html#L19

**Comment by Rybakov-Oleg** [comment]
https://github.com/Rybakov-Oleg/teahcing/commit/01965a59c076f5163f2201f37b0f1c4e0f7427fa

**Comment by Chkalov-Valerii** [comment]
Nicely done!
Try to avoid using empty "id"-s in the future.
