### ISSUE TITLE
type="submit" for submition buttons

### ISSUE THREAD

**Issue by Chkalov-Valerii** [Rybakov-Oleg/teahcing#5]
```
Try to avoid <input type="button"> at all. Use type="submit".
Use <input type="submit"> inside <form>-s.
Use <button> instead, if you outside <form>-s scope.
```
https://github.com/Rybakov-Oleg/teahcing/blob/8a667d3dfe0880d12647b856306399a675c9b01f/fg.html#L24

**Comment by Rybakov-Oleg** [comment]
https://github.com/Rybakov-Oleg/teahcing/commit/e5e31916ed4a765cbb935554966666149b48428e

**Comment by Chkalov-Valerii** [comment]
Ye, just like that!
Closing Issue
